# Generated by Django 3.0.6 on 2020-05-26 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_object', '0005_painting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='art_object.Artifact')),
                ('place', models.CharField(max_length=30)),
                ('width', models.FloatField(blank=True)),
                ('height', models.FloatField(blank=True)),
            ],
            bases=('art_object.artifact',),
        ),
        migrations.CreateModel(
            name='Sculpture',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='art_object.Artifact')),
                ('material', models.CharField(max_length=30)),
                ('height', models.FloatField(blank=True)),
                ('weight', models.FloatField(blank=True)),
            ],
            bases=('art_object.artifact',),
        ),
    ]
