# Generated by Django 3.0.6 on 2020-05-25 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art_Movement',
            fields=[
                ('movement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_name', models.CharField(max_length=40)),
                ('movement_description', models.TextField()),
                ('movement_begin', models.DateField(default='-')),
                ('movement_end', models.DateField(default='-')),
            ],
        ),
    ]
