# Generated by Django 3.0.6 on 2020-05-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_movement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art_movement',
            name='movement_begin',
        ),
        migrations.RemoveField(
            model_name='art_movement',
            name='movement_end',
        ),
        migrations.AddField(
            model_name='art_movement',
            name='movement_era',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
