# Generated by Django 3.0.6 on 2020-06-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_movement', '0002_auto_20200525_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_movement',
            name='movement_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
