# Generated by Django 3.0.6 on 2020-05-25 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=15)),
                ('user_password', models.CharField(max_length=20)),
                ('user_real_name', models.CharField(max_length=30)),
                ('user_surname', models.CharField(max_length=30)),
                ('user_picture', models.ImageField(blank=True, upload_to='')),
                ('user_birthdate', models.DateField()),
            ],
        ),
    ]
