# Generated by Django 3.0.6 on 2020-05-25 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.User')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
