# Generated by Django 3.0.6 on 2020-05-26 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
        ('art_object', '0004_artifact_museum_id'),
        ('art_movement', '0002_auto_20200525_2226'),
        ('artist', '0003_auto_20200527_0158'),
        ('user', '0003_favouriteartist_favouriteartmovement_favouriteartobject_favouritemuseum'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteartist',
            name='fav_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.Artist'),
        ),
        migrations.AddField(
            model_name='favouriteartist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='favouriteartmovement',
            name='fav_art_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='art_movement.Art_Movement'),
        ),
        migrations.AddField(
            model_name='favouriteartmovement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='favouriteartobject',
            name='fav_art_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='art_object.Artifact'),
        ),
        migrations.AddField(
            model_name='favouriteartobject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='favouritemuseum',
            name='fav_museum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='museum.Museum'),
        ),
        migrations.AddField(
            model_name='favouritemuseum',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
