# Generated by Django 3.0.6 on 2020-05-26 22:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('museum_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('museum_name', models.CharField(max_length=50)),
                ('museum_description', models.TextField(blank=True)),
                ('foundation_date', models.DateField()),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Place')),
            ],
        ),
        migrations.CreateModel(
            name='MuseumImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('museum_image', models.ImageField(upload_to='')),
                ('museum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.Museum')),
            ],
        ),
    ]
