# Generated by Django 3.0.6 on 2020-05-26 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_description', models.CharField(max_length=50)),
                ('place_country', models.CharField(max_length=50)),
                ('place_city', models.CharField(max_length=50)),
                ('place_zip', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
            ],
        ),
    ]
