# Generated by Django 3.0.6 on 2020-05-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_description',
            field=models.TextField(),
        ),
    ]
