# Generated by Django 3.0.6 on 2020-05-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist_image',
            old_name='image_id',
            new_name='of_artist',
        ),
    ]
