# Generated by Django 3.0.6 on 2020-06-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20200527_0146'),
        ('artist', '0004_ofartist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='place_death',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_death', to='place.Place'),
        ),
    ]
